### ISSUE TITLE
brew install fails due to cpantesters.org being blocked by OpenDNS

### ISSUE THREAD

**Issue by mcallaway** [sqitchers/homebrew-sqitch#41]
Trying to brew install sqitch I see:

    > brew install sqitch --with-sqlite-support
    ==> Installing sqitch from sqitchers/sqitch
    ==> Downloading http://cpan.cpantesters.org/authors/id/D/DW/DWHEELER/App-Sqitch-0.9998.tar.gz
    
    curl: (22) The requested URL returned error: 403 Forbidden
    Error: An exception occurred within a child process:
      DownloadError: Failed to download resource "sqitch"
    Download failed: http://cpan.cpantesters.org/authors/id/D/DW/DWHEELER/App-Sqitch-0.9998.tar.gz

Visiting http://cpan.cpantesters.org fails as OpenDNS flags it as possible malware.

Visiting https://cpan.cpantesters.org reveals an invalid SSL certificate.

I am able to download App-Sqitch via cpan.org. Perhaps that site should be used instead of cpantesters.org?

**Comment by theory** [comment]
Why not add TLS support?

**Comment by preaction** [comment]
I surely could, using Fastly as the rest of CPAN Testers is doing for SSL. I'm not sure if Fastly wants to host yet another CPAN mirror, since it already is the main CPAN mirror at cpan.org. I'm mostly here saying "CPAN Testers CPAN mirror SSL cert is broken" is incorrect.

I do still need to go around and beg for CPAN Testers to be delisted from malware tracking sites, which apparently means convincing hackers to stop using specifically my server's CPAN mirror to download CPAN modules? But, either way, using the primary fanout site is the best option for sqitch.

**Comment by theory** [comment]
Thanks @preaction. Assuming that `www.cpan.org` is the "primary fanout site", I think we're good here.
