### ISSUE TITLE
Calling brew install --env is disabled

### ISSUE THREAD

**Issue by naomiaro** [sqitchers/homebrew-sqitch#52]
Running from the README: 

`brew install sqitch --env=std --with-postgres-support --without-postgresql`

Receiving:

`Error: Calling brew install --env is disabled! Use `env :std` in specific formula files instead.`

**Comment by theory** [comment]
Hrm. Looks like they removed that option. From [the docs](https://docs.brew.sh/Building-Against-Non-Homebrew-Dependencies#today):

> If you wish to build against custom non-Homebrew dependencies that are provided by Homebrew (e.g. a non-Homebrew, non-macOS ruby) then you must create and maintain your own tap as these formulae will not be accepted in Homebrew/homebrew-core. Once you have done that you can specify env :std in the formula which will allow e.g. which ruby to access your existing PATH variable and allow compilation to link against this Ruby. You can also include a custom Requirement in your formula that more accurately describes the non-Homebrew software you build against.

This is kind of a bummer, because the idea here is to default to the Homebrew-installed dependencies, but give users the option to use others. If we add `env :std` to the formula (which we can, this is not a Homebrew tap), then it will always default to what it finds in the environment, whether Homebrew or not. Maybe that's for the best here? I honestly don't know.

**Comment by theory** [comment]
Hey @naomiaro, I am not a Homebrew user, but I *think* that 4e285fb will fix the issue. Can you give it a try?
